export const UPDATE_IMAGE = 'UPDATE_IMAGE_LIKED'

export const UPDATE_DATE = 'UPDATE_DATE'

export const SET_USER_IMAGES = 'SET_USER_IMAGES'

export const SET_INITIAL_PROMPTS = 'SET_INITIAL_PROMPTS'

export const SET_INITIAL_DATE = 'SET_INITIAL_DATE'

export const LOGIN = 'LOGIN'

export const LOGOUT = 'LOGOUT'

export const ADD_IMAGE = 'ADD_IMAGE'

export const SET_CURRENT_PROMPT_ID = 'SET_CURRENT_PROMPT_ID'
