export const UPDATE_IMAGE_LIKED = 'UPDATE_IMAGE_LIKED'

export const UPDATE_DATE = 'UPDATE_DATE'

export const DELETE_COMMENT = 'DELETE_COMMENT'

export const UPDATE_COMMENT_EDITING = 'UPDATE_COMMENT_EDITING'

export const EDIT_COMMENT = 'EDIT_COMMENT'

export const SET_USER_IMAGES = 'SET_USER_IMAGES'

export const SET_INITIAL_PROMPTS = 'SET_INITIAL_PROMPTS'

export const SET_INITIAL_DATE = 'SET_INITIAL_DATE'

export const LOGIN = 'LOGIN'

export const LOGOUT = 'LOGOUT'

export const ADD_IMAGE = 'ADD_IMAGE'

export const SET_CURRENT_PROMPT_ID = 'SET_CURRENT_PROMPT_ID'
